# Generated by Django 2.0.2 on 2018-04-15 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('invoice_number', models.IntegerField(default='81593', primary_key=True, serialize=False, verbose_name='Rechnugsnummer')),
            ],
            options={
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Client', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(blank=True, max_length=50, verbose_name='Firma')),
                ('Company_Email', models.EmailField(blank=True, max_length=254, verbose_name='Firma Email')),
                ('Company_Phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon Firma')),
                ('Company_PostalCode', models.CharField(blank=True, max_length=6, verbose_name='Postleitzahl')),
                ('Company_City', models.CharField(blank=True, max_length=20, verbose_name='Stadt')),
                ('Company_Street', models.CharField(blank=True, max_length=20, verbose_name='Strasse')),
                ('Contact_LastName', models.CharField(blank=True, max_length=50, verbose_name='Nachname')),
                ('Contact_FirstName', models.CharField(blank=True, max_length=50, verbose_name='Vorname')),
                ('Contact_Email', models.EmailField(blank=True, max_length=254, verbose_name='Email Ansprechpartner')),
                ('Contact_Phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon Ansprechpartner')),
            ],
            options={
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Inventory', models.AutoField(primary_key=True, serialize=False)),
                ('Inventory_Name', models.CharField(max_length=50, verbose_name='Bauteil')),
                ('Inventory_Description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preis')),
            ],
            options={
                'verbose_name_plural': 'Lager',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Description', models.TextField(blank=True, verbose_name='Projekt Beschreibung')),
                ('Date_ProjectEntry', models.DateField(default=datetime.date(2018, 4, 15), verbose_name='Eingangsdatum')),
                ('Date_Construction', models.DateField(blank=True, null=True, verbose_name='Aufbaudatum')),
                ('Date_Dismant', models.DateField(blank=True, null=True, verbose_name='Abbaudatum')),
                ('Date_SignOff', models.DateField(blank=True, null=True, verbose_name='Abmeldedatum')),
                ('Project_Amount', models.IntegerField(blank=True, null=True, verbose_name='Menge')),
                ('Project_Client', models.ForeignKey(on_delete='SET_NULL', to='geruestproject.Client', verbose_name='Firma')),
                ('Project_Item', models.ForeignKey(default='1', on_delete='SET_NULL', related_name='Project_Item', to='geruestproject.Inventory', verbose_name='Bauteil')),
                ('Project_Kupplung', models.ForeignKey(default=1, on_delete='SET_NULL', related_name='Project_Kupplung', to='geruestproject.Inventory', verbose_name='Kupplung')),
            ],
            options={
                'verbose_name_plural': 'Projekte',
            },
        ),
        migrations.AddField(
            model_name='billing',
            name='invoice_client',
            field=models.ForeignKey(on_delete='SET_NULL', to='geruestproject.Project', verbose_name='Kunde'),
        ),
    ]
