# Generated by Django 2.0.4 on 2019-01-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(blank=True, max_length=50, verbose_name='Firma')),
                ('Company_Email', models.EmailField(blank=True, max_length=254, verbose_name='Firma Email')),
                ('Company_Phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon Firma')),
                ('Company_PostalCode', models.CharField(blank=True, max_length=6, verbose_name='Postleitzahl')),
                ('Company_City', models.CharField(blank=True, max_length=20, verbose_name='Stadt')),
                ('Company_Street', models.CharField(blank=True, max_length=20, verbose_name='Strasse')),
                ('Contact_LastName', models.CharField(blank=True, max_length=50, verbose_name='Nachname')),
                ('Contact_FirstName', models.CharField(blank=True, max_length=50, verbose_name='Vorname')),
                ('Contact_Email', models.EmailField(blank=True, max_length=254, verbose_name='Email Ansprechpartner')),
                ('Contact_Phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon Ansprechpartner')),
            ],
            options={
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laenge', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Laenge')),
                ('Breite', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Breite')),
                ('Hoehe', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Hoehe')),
                ('Stueck', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Stueck')),
                ('Stunde', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Stunde')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Geruestbuch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Geruestnummer', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Gerüstnummer')),
                ('Anforderer', models.CharField(blank=True, max_length=10, verbose_name='Anforderer')),
                ('Ansprechpartner', models.CharField(blank=True, max_length=10, verbose_name='Ansprechpartner')),
                ('AnlageEquipment', models.CharField(blank=True, max_length=10, verbose_name='Anlage / Equipment')),
                ('Ebene', models.CharField(blank=True, max_length=10, verbose_name='Ebene')),
                ('Oertlichkeit', models.CharField(blank=True, max_length=10, verbose_name='Örtlichkeit')),
                ('Grund', models.CharField(blank=True, max_length=10, verbose_name='Grund')),
                ('L', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Länge')),
                ('B', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Breite')),
                ('H', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Höhe')),
                ('Firma', models.ForeignKey(on_delete='PROTECT', to='geruestproject.Client', verbose_name='Firma')),
            ],
            options={
                'verbose_name_plural': 'Gerüste',
            },
        ),
        migrations.CreateModel(
            name='Inventar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Bauteil')),
                ('Einheit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('Beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('Preis', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preis')),
                ('Einheit_Miete', models.CharField(max_length=50, verbose_name='Einheit Miete')),
                ('Beschreibung_Miete', models.CharField(max_length=50, verbose_name='Beschreibung Miete')),
                ('Preis_Miete', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preis Miete')),
            ],
            options={
                'verbose_name_plural': 'Leistungsverzeichnis',
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('Project_Name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Projekt Name')),
            ],
            options={
                'verbose_name_plural': 'Projekte',
            },
        ),
        migrations.AddField(
            model_name='geruestbuch',
            name='Projekt',
            field=models.ForeignKey(on_delete='PROTECT', to='geruestproject.Projekt', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='Equipment',
            field=models.ForeignKey(on_delete='SET_NULL', to='geruestproject.Inventar', verbose_name='Inventar'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='Geruestnummer',
            field=models.ForeignKey(on_delete='SET_NULL', to='geruestproject.Geruestbuch', verbose_name='Geruestnummer'),
        ),
    ]
