# Generated by Django 2.0.4 on 2018-04-15 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_number',
            field=models.IntegerField(default='45802', primary_key=True, serialize=False, verbose_name='Rechnugsnummer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Date_ProjectEntry',
            field=models.DateField(default=datetime.date(2018, 4, 16), verbose_name='Eingangsdatum'),
        ),
    ]
