# Generated by Django 2.0.4 on 2019-01-19 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geruestbuch',
            name='Abmeldedatum',
            field=models.DateField(blank=True, null=True, verbose_name='Abmeldedatum'),
        ),
        migrations.AddField(
            model_name='geruestbuch',
            name='Anmeldedatum',
            field=models.DateField(default=datetime.date(2019, 1, 19), verbose_name='Anmeldedatum'),
        ),
        migrations.AddField(
            model_name='geruestbuch',
            name='Nutzungsbeginn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nutzungsbeginn'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Anforderer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Anforderer'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='AnlageEquipment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Anlage / Equipment'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Ansprechpartner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ansprechpartner'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Ebene',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ebene'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Grund',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grund'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Oertlichkeit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Örtlichkeit'),
        ),
    ]
