# Generated by Django 2.0.4 on 2018-12-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geruestbuch',
            name='Eingangsdatum',
            field=models.DateField(default=datetime.date(2018, 12, 22), verbose_name='Eingangsdatum'),
        ),
    ]
