# Generated by Django 2.0.4 on 2019-01-22 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0002_auto_20190119_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Firmen'},
        ),
        migrations.AddField(
            model_name='inventar',
            name='Leistungsposition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='LV Positionsnummer'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Anmeldedatum',
            field=models.DateField(default=datetime.date(2019, 1, 22), verbose_name='Anmeldedatum'),
        ),
        migrations.AlterField(
            model_name='inventar',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='LV Positionsname'),
        ),
    ]
