# Generated by Django 2.0.4 on 2018-12-23 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0002_auto_20181222_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geruestbuch',
            name='Eingangsdatum',
            field=models.DateField(default=datetime.date(2018, 12, 23), verbose_name='Eingangsdatum'),
        ),
    ]
