# Generated by Django 2.0.4 on 2018-04-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0002_auto_20180416_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_number',
            field=models.IntegerField(default='66918', primary_key=True, serialize=False, verbose_name='Rechnugsnummer'),
        ),
    ]
