# Generated by Django 2.0.4 on 2019-01-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0003_auto_20190122_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='geruestbuch',
            name='Geruestbezeichner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gerüstbezeichner'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Anforderer',
            field=models.CharField(blank=True, max_length=50, verbose_name='PU-Manager'),
        ),
    ]
