# Generated by Django 2.0.4 on 2018-04-16 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0003_auto_20180416_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_number',
            field=models.IntegerField(default='28530', primary_key=True, serialize=False, verbose_name='Rechnugsnummer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Date_ProjectEntry',
            field=models.DateField(default=datetime.date(2018, 4, 17), verbose_name='Eingangsdatum'),
        ),
    ]
