# Generated by Django 2.0.4 on 2019-01-22 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0004_auto_20190122_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geruestbuch',
            name='Geruestnummer',
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Anmeldedatum',
            field=models.DateField(default=datetime.date(2019, 1, 23), verbose_name='Anmeldedatum'),
        ),
    ]
