# Generated by Django 2.0.4 on 2018-04-18 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0004_auto_20180417_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='invoice_client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Leistungsverzeichnis'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Gerüstliste'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='Project_Amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Project_Item',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Project_Kupplung',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Inventory',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='PosNr.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Inventory_Name',
            field=models.CharField(max_length=50, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Date_ProjectEntry',
            field=models.DateField(default=datetime.date(2018, 4, 19), verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Auftragsnr.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_Description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
