# Generated by Django 2.0.4 on 2019-01-24 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0006_auto_20190123_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='geruestbuch',
            name='InternalID',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shell Interne ID'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Anmeldedatum',
            field=models.DateField(default=datetime.date(2019, 1, 24), verbose_name='Anmeldedatum'),
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Geruestbezeichner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gerüstnummer'),
        ),
    ]
