# Generated by Django 2.0.4 on 2019-01-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0007_auto_20190124_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geruestbuch',
            name='InternalID',
        ),
        migrations.AlterField(
            model_name='geruestbuch',
            name='Geruestbezeichner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gerüstbezeichner'),
        ),
    ]
