# Generated by Django 2.0.4 on 2019-01-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0008_auto_20190124_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='geruestbuch',
            name='InterneID',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shell Interne ID'),
        ),
    ]
