# Generated by Django 2.0.4 on 2019-01-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geruestproject', '0009_geruestbuch_interneid'),
    ]

    operations = [
        migrations.AddField(
            model_name='geruestbuch',
            name='Positionsart',
            field=models.CharField(blank=True, max_length=50, verbose_name='Positionsart'),
        ),
    ]
